### ISSUE TITLE
Lambda bug

### ISSUE THREAD

**Issue by gHashTag** [react-native-village/aws-amplify-react-hooks#51]
Who can advise on Lambda? I make the application the steps of this article and as a result, SMS do not come.
---
Кто по Lambda может проконсультировать? Делаю приложение по шагам этой статьи и в итоге смс не приходят. 

https://techinscribed.com/passwordless-phone-number-authentication-using-aws-amplify-cognito/

**Comment by sanioka** [comment]
Аналогичная проблема, что делать?

**Comment by gHashTag** [comment]
Это решение рекомендовали, но сам не пробывал
  https://github.com/ykbryan/aws-amplify-react-auth-otp

**Comment by sanioka** [comment]
Спасибо!
Если перейти на их демку https://otp.bryanchua.io, то да, смски приходят отлично 🔥

**Comment by sanioka** [comment]
Причина, по которой смс не приходят из амазона:
— Для лямбда функции нужно указать права доступа для вызова SNS сервиса.
— Если в консоли SNS вручную смс ки не отправляются, нужно написать в саппорт и запросить увеличение лимита с $1 d месяц на побольше. Вместе с запросом они включат отправку смс из сервиса SNS в принципе.

**Comment by gHashTag** [comment]
@sanioka можешь написать гайд с пошаговой инструкцией? Я его на хабре бустну и тебя как автора пропиарю.

**Comment by sanioka** [comment]
Гайд уже написан на английском:
https://blog.bitsrc.io/building-otp-authentication-with-reactjs-and-aws-amplify-c5fd2e517fac

Можешь перевести его, если хочешь))
